#!/usr/bin/env python3
"""Swarm Agents — Planner, Researcher, Coder, Reviewer, Optimizer with parallel execution."""

import json, time, threading, random
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional, Callable
from dataclasses import dataclass, field

from .swarm_memory import SwarmMemory, get_swarm_memory


@dataclass
class AgentResult:
    agent: str = ""
    task: str = ""
    output: str = ""
    confidence: float = 0.5
    latency_ms: int = 0
    error: str = ""


class SwarmAgent:
    """Base class for all swarm agents."""

    def __init__(self, name: str, role: str, memory: SwarmMemory):
        self.name = name
        self.role = role
        self.memory = memory
        self.results: List[AgentResult] = []

    def execute(self, task: str, context: Dict = {}) -> AgentResult:
        raise NotImplementedError

    def run(self, task: str, context: Dict = {}, callback: Callable = None) -> AgentResult:
        start = time.time()
        self.memory.event(self.name, "started", task[:100])

        try:
            result = self.execute(task, context)
            result.latency_ms = int((time.time() - start) * 1000)
            self.results.append(result)
            self.memory.put(f"{self.name}_last_result", result.output, self.name)
            self.memory.event(self.name, "completed", f"confidence={result.confidence:.2f}")
            if callback:
                callback(result)
            return result
        except Exception as e:
            self.memory.event(self.name, "error", str(e))
            return AgentResult(agent=self.name, task=task, error=str(e),
                             latency_ms=int((time.time() - start) * 1000))

    def stats(self) -> Dict:
        return {"name": self.name, "role": self.role, "tasks": len(self.results)}


class PlannerAgent(SwarmAgent):
    """Breaks goals into subtasks and assigns to agents."""

    def __init__(self, memory: SwarmMemory):
        super().__init__("Planner", "planner", memory)

    def execute(self, task: str, context: Dict = {}) -> AgentResult:
        phases = ["recon", "research", "analyze", "code", "review", "optimize"]

        steps = []
        for i, phase in enumerate(phases):
            steps.append({
                "step": i + 1, "phase": phase,
                "agent": f"{phase.title()}Agent",
                "action": f"Execute {phase} on: {task}",
                "depends_on": steps[-1]["step"] if steps else None,
            })

        plan = {"target": task, "steps": steps, "estimated_phases": len(phases)}
        self.memory.put("current_plan", plan, self.name)

        return AgentResult(agent=self.name, task=task,
                          output=json.dumps(plan, indent=2),
                          confidence=0.85)


class ResearcherAgent(SwarmAgent):
    """Collects information, searches memory, retrieves documents."""

    def __init__(self, memory: SwarmMemory):
        super().__init__("Researcher", "researcher", memory)

    def execute(self, task: str, context: Dict = {}) -> AgentResult:
        findings = []

        # Search swarm memory
        mem_keys = list(self.memory._store.keys())
        relevant = [k for k in mem_keys if any(w in k.lower() for w in task.lower().split())]
        for k in relevant[:5]:
            findings.append({"source": "swarm_memory", "key": k,
                            "value": str(self.memory.get(k, ""))[:300]})

        # Search local tools
        tool_hints = {
            "nmap": "Network scanner — use nmap -sV -sC",
            "sql": "Use sqlmap for SQL injection testing",
            "web": "Use nikto, gobuster for web scanning",
            "exploit": "Use metasploit, searchsploit for exploitation",
            "payload": "Use msfvenom for payload generation",
        }
        for kw, hint in tool_hints.items():
            if kw in task.lower():
                findings.append({"source": "tool_registry", "key": kw, "value": hint})

        research = {
            "query": task,
            "findings": findings,
            "sources_searched": len(findings),
            "recommendation": findings[0]["value"] if findings else "Conduct manual research",
        }

        return AgentResult(agent=self.name, task=task,
                          output=json.dumps(research, indent=2),
                          confidence=0.75 if findings else 0.4)


class CoderAgent(SwarmAgent):
    """Generates code, patches, and automation scripts."""

    def __init__(self, memory: SwarmMemory):
        super().__init__("Coder", "coder", memory)

    def execute(self, task: str, context: Dict = {}) -> AgentResult:
        lang = context.get("language", "python")

        templates = {
            "python": f'''#!/usr/bin/env python3
"""Auto-generated by Swarm CoderAgent for: {task}"""
import subprocess, sys

def main():
    target = sys.argv[1] if len(sys.argv) > 1 else "localhost"
    print(f"[+] Starting operation on {{target}}")
    # TODO: Implement {task}
    print("[+] Operation complete")

if __name__ == "__main__":
    main()''',
            "bash": f'''#!/bin/bash
# Auto-generated by Swarm CoderAgent
TARGET="${{1:-localhost}}"
echo "[+] Scanning $TARGET"
nmap -sV -sC "$TARGET"
echo "[+] Done"''',
        }

        code = templates.get(lang, templates["python"])
        self.memory.put(f"code_{task[:20]}", code, self.name)

        return AgentResult(agent=self.name, task=task,
                          output=code,
                          confidence=0.8)


class ReviewerAgent(SwarmAgent):
    """Scores outputs, verifies quality, identifies weaknesses."""

    def __init__(self, memory: SwarmMemory):
        super().__init__("Reviewer", "reviewer", memory)

    def execute(self, task: str, context: Dict = {}) -> AgentResult:
        outputs = context.get("agent_outputs", {})
        scores: Dict[str, Dict] = {}

        for agent_name, output in outputs.items():
            has_content = len(output) > 50
            has_structure = any(kw in output.lower() for kw in ["step", "plan", "strategy", "code", "result"])
            has_tools = any(t in output.lower() for t in ["nmap", "sqlmap", "python", "bash"])

            scores[agent_name] = {
                "score": round((0.4 * has_content + 0.3 * has_structure + 0.3 * has_tools) * 100),
                "has_content": has_content,
                "has_structure": has_structure,
                "has_tools": has_tools,
            }

        best = max(scores.items(), key=lambda x: x[1]["score"]) if scores else ("none", {})

        return AgentResult(agent=self.name, task=task,
                          output=json.dumps({"scores": scores, "best_agent": best[0]}, indent=2),
                          confidence=0.7)


class OptimizerAgent(SwarmAgent):
    """Improves prompts, optimizes tool selection, recommends models."""

    def __init__(self, memory: SwarmMemory):
        super().__init__("Optimizer", "optimizer", memory)

    def execute(self, task: str, context: Dict = {}) -> AgentResult:
        recommendations = {
            "task": task,
            "model_suggestion": "deepseek-v4-flash" if len(task) < 50 else "deepseek-v4-pro",
            "strategy_suggestion": "multi-agent" if "complex" in task.lower() else "single-agent",
            "tool_suggestions": [],
            "prompt_improvement": f"Be more specific. Include tool names and expected outputs for: {task}",
        }

        tool_map = {
            "scan": ["nmap", "masscan"], "web": ["gobuster", "nikto", "wpscan"],
            "sql": ["sqlmap"], "exploit": ["metasploit", "searchsploit"],
            "password": ["hydra", "john"], "payload": ["msfvenom"],
        }
        for kw, tools in tool_map.items():
            if kw in task.lower():
                recommendations["tool_suggestions"].extend(tools)

        return AgentResult(agent=self.name, task=task,
                          output=json.dumps(recommendations, indent=2),
                          confidence=0.8)
